### ISSUE TITLE
AX: Add pre-commit check for orphaned TypeScript files in composite projects

### ISSUE THREAD

**Issue by Guffawaffle** [Guffawaffle/lex#547]
## Problem

During the batch ingestion API merge (PR #545), a new file `src/memory/batch.ts` was added but not included in the TypeScript composite project references. This caused a build failure that was only caught after the PR was merged.

**Root cause**: Copilot agents (and humans) adding new `.ts` files to subdirectories without understanding the composite TypeScript structure.

## Observed Anti-Pattern

1. Agent adds `src/memory/batch.ts`
2. Agent does NOT update `src/memory/store/tsconfig.json` to include the new file
3. PR passes lint (files not compiled yet)
4. Build fails after merge with TS6307: "File not listed within project"

## Proposed Solution

Add a pre-commit or CI check that detects orphaned TypeScript files in the `src/` tree.

### Option A: Script Check

```bash
# scripts/check-ts-orphans.sh
# Find .ts files not covered by any tsconfig.json include pattern
```

### Option B: TypeScript Composite Validation

```bash
# Add to local-ci
tsc -b --dry --listEmittedFiles 2>&1 | grep -E "error TS6307" && exit 1
```

### Option C: Document Pattern

Update copilot-instructions.md with guidance:
```markdown
## TypeScript Composite Projects

This repo uses TypeScript project references. When adding a new `.ts` file:
1. Check the nearest `tsconfig.json` in parent directory
2. Ensure file is in `include` array or add it
3. If importing from other subdirs, add `references` entries
```

## Acceptance Criteria

- [ ] Build failures from orphaned .ts files are caught before merge
- [ ] Clear error message guides to solution
- [ ] Documentation updated if needed

## Labels

`ax`, `dx`, `ci`
